# Generated by Django 2.2.24 on 2021-08-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeightChanges',
            new_name='WeightChange',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
