# Generated by Django 2.2.24 on 2021-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210821_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightchange',
            name='date_time',
            field=models.CharField(max_length=14),
        ),
    ]
