# Generated by Django 3.2.6 on 2021-09-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210823_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightchange',
            name='date_time',
            field=models.CharField(max_length=25),
        ),
    ]
